<a href="https://colab.research.google.com/github/SEAFromJahu/PnP-OfficeAddins/blob/main/soulcode_g7b2b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instale com o pip o conector-python-mysql

In [31]:
# prompt: Instale com o pip o conector-python-mysql
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.10/dist-packages (9.1.0)

In [32]:
import mysql.connector
import pandas as pd

In [5]:
!curl ipecho.net/plain

34.168.231.133

In [33]:
host = '34.135.182.58'
user = 'root'
password = 'g7b@t@tasSabyas'
database = 'g7_b_to_b_db'

In [34]:
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
)
cursor = connection.cursor()
query = '''
SELECT * FROM Vendas;
'''
cursor.execute(query)
result = cursor.fetchall()
df = pd.DataFrame(result, columns=cursor.column_names)
cursor.close()
connection.close()

In [35]:
df.head()

,idVenda,Data_Venda,idCliente,idProduto,Quantidade,Valor_Total,Região,Setor,idVendedor
0,1,2022-12-09,31,9,4,2357.08,Sudeste,Manufatura,13
1,2,2022-10-19,170,9,9,5303.43,Nordeste,Tecnologia,13
2,3,2023-01-14,178,4,3,8564.37,Sudeste,Tecnologia,3
3,4,2023-03-12,154,6,3,9205.14,Sul,Tecnologia,20
4,5,2023-03-06,135,5,7,26317.97,Sudeste,Finanças,18

In [36]:
df.describe()

           idVenda   idCliente    idProduto   Quantidade   idVendedor
count  1000.000000  1000.00000  1000.000000  1000.000000  1000.000000
mean    500.500000    94.89900     5.699000     5.389000    10.714000
std     288.819436    56.96627     2.913226     2.860045     5.847598
min       1.000000     1.00000     1.000000     1.000000     1.000000
25%     250.750000    42.00000     3.000000     3.000000     6.000000
50%     500.500000    95.00000     6.000000     5.000000    11.000000
75%     750.250000   144.00000     8.000000     8.000000    16.000000
max    1000.000000   200.00000    10.000000    10.000000    20.000000